/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    products: Product;
    media: Media;
    categories: Category;
    tags: Tag;
    'blog-posts': BlogPost;
    slides: Slide;
    'static-pages': StaticPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    slides: SlidesSelect<false> | SlidesSelect<true>;
    'static-pages': StaticPagesSelect<false> | StaticPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'store-info': StoreInfo;
    pages: Page;
    'product-card-settings': ProductCardSetting;
    'theme-settings': ThemeSetting;
  };
  globalsSelect: {
    'store-info': StoreInfoSelect<false> | StoreInfoSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'product-card-settings': ProductCardSettingsSelect<false> | ProductCardSettingsSelect<true>;
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * The unique identifier from Medusa
   */
  medusa_id: string;
  /**
   * The product title
   */
  title: string;
  /**
   * URL-friendly unique identifier
   */
  handle: string;
  /**
   * Product subtitle
   */
  subtitle?: string | null;
  /**
   * Detailed product description
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Product thumbnail image
   */
  thumbnail?: (number | null) | Media;
  /**
   * Gallery of product images
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * SEO-related fields for better search visibility
   */
  seo?: {
    meta_title?: string | null;
    meta_description?: string | null;
    meta_keywords?: string | null;
  };
  options?:
    | {
        title: string;
        /**
         * The unique identifier for the option from Medusa
         */
        medusa_id: string;
        id?: string | null;
      }[]
    | null;
  variants?:
    | {
        title: string;
        /**
         * The unique identifier for the variant from Medusa
         */
        medusa_id: string;
        option_values?:
          | {
              /**
               * The unique identifier for the option value from Medusa
               */
              medusa_id: string;
              /**
               * The unique identifier for the option from Medusa
               */
              medusa_option_id: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Kategorie produktów i wpisów blogowych
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * The unique identifier from Medusa
   */
  medusa_id?: string | null;
  name: string;
  /**
   * Przyjazny URL (np. elektronika, odziez). Generowany automatycznie z nazwy.
   */
  slug: string;
  description?: string | null;
  /**
   * Obraz wyświetlany jako tło przycisku prowadzącego do produktów z tej kategorii.
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tagi przypisywane do wpisów blogowych
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Kolor wyświetlany jako etykieta tagu (format HEX, np. #6366f1).
   */
  color: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Wpisy blogowe przypisywane do kategorii i oznaczane tagami
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Przyjazny URL wpisu (generowany automatycznie z tytułu).
   */
  slug: string;
  /**
   * Wyświetlany na listingu bloga jako krótki opis wpisu.
   */
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Kategoria z której pochodzi wpis (ta sama co kategorie produktów).
   */
  category?: (number | null) | Category;
  /**
   * Wybierz tagi z listy. Tagi tworzone są w sekcji Tagi panelu.
   */
  tags?: (number | Tag)[] | null;
  /**
   * Data i godzina publikacji wpisu.
   */
  publishedAt?: string | null;
  status: 'draft' | 'published' | 'archived';
  seo?: {
    meta_title?: string | null;
    meta_description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Slajdy wyświetlane na karuzeli/sliderze strony głównej
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slides".
 */
export interface Slide {
  id: number;
  title: string;
  /**
   * Krótki tekst wyświetlany pod tytułem na slajdzie.
   */
  subtitle?: string | null;
  /**
   * Obraz wyświetlany jako pełnoekranowe tło slajdu.
   */
  backgroundImage: number | Media;
  /**
   * Tekst na przycisku Call-to-Action (np. 'Sprawdź ofertę').
   */
  ctaLabel?: string | null;
  /**
   * URL do którego prowadzi przycisk CTA (np. /kategoria/elektronika).
   */
  ctaUrl?: string | null;
  /**
   * Niższa liczba = wyświetlany wcześniej. Domyślnie 0.
   */
  order?: number | null;
  /**
   * Odznacz aby ukryć slajd bez jego usuwania.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kreator stron statycznych (np. O nas, Regulamin, Polityka prywatności)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages".
 */
export interface StaticPage {
  id: number;
  title: string;
  /**
   * Przyjazny URL strony (np. o-nas, regulamin). Generowany automatycznie z tytułu.
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'published';
  seo?: {
    meta_title?: string | null;
    meta_description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'slides';
        value: number | Slide;
      } | null)
    | ({
        relationTo: 'static-pages';
        value: number | StaticPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  medusa_id?: T;
  title?: T;
  handle?: T;
  subtitle?: T;
  description?: T;
  thumbnail?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        meta_title?: T;
        meta_description?: T;
        meta_keywords?: T;
      };
  options?:
    | T
    | {
        title?: T;
        medusa_id?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        title?: T;
        medusa_id?: T;
        option_values?:
          | T
          | {
              medusa_id?: T;
              medusa_option_id?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  medusa_id?: T;
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  category?: T;
  tags?: T;
  publishedAt?: T;
  status?: T;
  seo?:
    | T
    | {
        meta_title?: T;
        meta_description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slides_select".
 */
export interface SlidesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  backgroundImage?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-pages_select".
 */
export interface StaticPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  status?: T;
  seo?:
    | T
    | {
        meta_title?: T;
        meta_description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Globalne informacje o sklepie widoczne w stopce, meta tagach i na stronie kontaktowej.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-info".
 */
export interface StoreInfo {
  id: number;
  storeName: string;
  logo?: (number | null) | Media;
  tagline?: string | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    /**
     * Pełny adres siedziby firmy.
     */
    address?: string | null;
  };
  socialMedia?: {
    facebook?: string | null;
    instagram?: string | null;
    tiktok?: string | null;
    youtube?: string | null;
    x?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    favicon?: (number | null) | Media;
  };
  businessInfo?: {
    companyName?: string | null;
    nip?: string | null;
    regon?: string | null;
    bankAccount?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Konstruuj strony sklepu za pomocą gotowych bloków (karuzele, blogi, kategorie).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Bloki wyświetlane na stronie głównej sklepu.
   */
  homePage?: {
    /**
     * Dodaj i układaj sekcje strony głównej. Możesz dodawać karuzele produktów, karuzele kategorii oraz sekcję najnowszych wpisów blogowych.
     */
    blocks?:
      | (
          | {
              /**
               * Tytuł wyświetlany nad karuzelą produktów.
               */
              heading?: string | null;
              /**
               * Ikona z biblioteki lucide-react wyświetlana obok nagłówka.
               */
              icon?:
                | (
                    | 'none'
                    | 'ShoppingBag'
                    | 'Star'
                    | 'Flame'
                    | 'Tag'
                    | 'Gift'
                    | 'Zap'
                    | 'Heart'
                    | 'Award'
                    | 'TrendingUp'
                    | 'Sparkles'
                    | 'Box'
                    | 'Package'
                    | 'ShoppingCart'
                    | 'Percent'
                    | 'Layers'
                  )
                | null;
              /**
               * Skąd pobierać produkty do karuzeli.
               */
              sourceType: 'category' | 'collection' | 'manual';
              /**
               * Wybierz kategorię z której pobierane będą produkty.
               */
              category?: (number | null) | Category;
              /**
               * Wpisz handle kolekcji z Medusa (np. 'new-arrivals').
               */
              collectionHandle?: string | null;
              /**
               * Ręcznie wybierz produkty do wyświetlenia w karuzeli.
               */
              manualProducts?: (number | Product)[] | null;
              /**
               * Ile produktów widać jednocześnie w karuzeli (domyślnie 6).
               */
              visibleCount?: number | null;
              /**
               * Wyświetla przycisk prowadzący do strony ze wszystkimi produktami danej kategorii/kolekcji.
               */
              showViewAllButton?: boolean | null;
              /**
               * Tekst na przycisku prowadzącym do pełnej listy produktów.
               */
              viewAllLabel?: string | null;
              /**
               * URL przycisku (np. /store lub /categories/elektronika).
               */
              viewAllUrl?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'product-carousel';
            }
          | {
              /**
               * Tytuł wyświetlany nad karuzelą kategorii.
               */
              heading?: string | null;
              /**
               * Ikona z biblioteki lucide-react wyświetlana obok nagłówka.
               */
              icon?:
                | (
                    | 'none'
                    | 'Grid'
                    | 'LayoutGrid'
                    | 'List'
                    | 'Folders'
                    | 'Tag'
                    | 'Layers'
                    | 'Shapes'
                    | 'Sparkles'
                    | 'Compass'
                  )
                | null;
              /**
               * Skąd pobierać kategorie do karuzeli.
               */
              sourceType: 'all' | 'manual';
              /**
               * Ręcznie wybierz kategorie do wyświetlenia w karuzeli.
               */
              categories?: (number | Category)[] | null;
              /**
               * Ile kategorii widać jednocześnie w karuzeli (domyślnie 4).
               */
              visibleCount?: number | null;
              /**
               * Przedrostek URL dla linków do kategorii (np. /categories lub /store). Slug kategorii zostanie dołączony automatycznie.
               */
              categoryUrlPrefix?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'category-carousel';
            }
          | {
              /**
               * Tytuł wyświetlany nad sekcją bloga.
               */
              heading?: string | null;
              /**
               * Ikona z biblioteki lucide-react wyświetlana obok nagłówka.
               */
              icon?:
                | ('none' | 'BookOpen' | 'FileText' | 'Newspaper' | 'PenLine' | 'Rss' | 'MessageSquare' | 'Library')
                | null;
              /**
               * Ile najnowszych wpisów blogowych wyświetlić (domyślnie 3).
               */
              postsCount?: number | null;
              /**
               * Jeśli zaznaczone, wpisy będą filtrowane do wybranej kategorii.
               */
              filterByCategory?: boolean | null;
              /**
               * Pokazuj wpisy tylko z tej kategorii.
               */
              category?: (number | null) | Category;
              /**
               * Wyświetla przycisk prowadzący do strony ze wszystkimi wpisami blogu.
               */
              showViewAllButton?: boolean | null;
              /**
               * Tekst na przycisku prowadzącym do bloga.
               */
              viewAllLabel?: string | null;
              /**
               * URL przycisku (np. /blog).
               */
              viewAllUrl?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'latest-blogs';
            }
        )[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Dostosuj wygląd kart produktów wyświetlanych na karuzeli i w listingach.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-card-settings".
 */
export interface ProductCardSetting {
  id: number;
  image?: {
    show?: boolean | null;
    /**
     * Proporcje zdjęcia produktu na karcie.
     */
    aspectRatio?: ('1/1' | '4/3' | '3/4' | '16/9' | '2/3') | null;
    borderRadius?: ('0px' | '4px' | '8px' | '12px' | '16px' | '9999px') | null;
  };
  /**
   * Styl wyświetlania nazwy produktu.
   */
  productName?: {
    /**
     * Czy nazwę produktu ma być wyświetlana na karcie produktu?
     */
    show?: boolean | null;
    /**
     * Rozmiar tekstu dla: nazwę produktu.
     */
    fontSize?:
      | (
          | '10px'
          | '11px'
          | '12px'
          | '13px'
          | '14px'
          | '15px'
          | '16px'
          | '18px'
          | '20px'
          | '22px'
          | '24px'
          | '28px'
          | '32px'
        )
      | null;
    /**
     * Grubość tekstu dla: nazwę produktu.
     */
    fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
    /**
     * Kolor tekstu w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.8)). Dotyczy: nazwę produktu.
     */
    color?: string | null;
    /**
     * Po przekroczeniu limitu tekst zostanie przycięty wielokropkiem.
     */
    maxLines?: ('1' | '2' | '3' | 'none') | null;
  };
  /**
   * Styl wyświetlania etykiety kategorii produktu.
   */
  category?: {
    /**
     * Czy kategorię produktu ma być wyświetlana na karcie produktu?
     */
    show?: boolean | null;
    /**
     * Rozmiar tekstu dla: kategorię produktu.
     */
    fontSize?:
      | (
          | '10px'
          | '11px'
          | '12px'
          | '13px'
          | '14px'
          | '15px'
          | '16px'
          | '18px'
          | '20px'
          | '22px'
          | '24px'
          | '28px'
          | '32px'
        )
      | null;
    /**
     * Grubość tekstu dla: kategorię produktu.
     */
    fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
    /**
     * Kolor tekstu w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.8)). Dotyczy: kategorię produktu.
     */
    color?: string | null;
  };
  /**
   * Styl wyświetlania ceny produktu.
   */
  price?: {
    /**
     * Czy cenę produktu ma być wyświetlana na karcie produktu?
     */
    show?: boolean | null;
    /**
     * Rozmiar tekstu dla: cenę produktu.
     */
    fontSize?:
      | (
          | '10px'
          | '11px'
          | '12px'
          | '13px'
          | '14px'
          | '15px'
          | '16px'
          | '18px'
          | '20px'
          | '22px'
          | '24px'
          | '28px'
          | '32px'
        )
      | null;
    /**
     * Grubość tekstu dla: cenę produktu.
     */
    fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
    /**
     * Kolor tekstu w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.8)). Dotyczy: cenę produktu.
     */
    color?: string | null;
    /**
     * Wyświetla przekreśloną cenę oryginalną gdy produkt ma cenę promocyjną.
     */
    showOriginalPrice?: boolean | null;
    /**
     * Kolor przekreślonej ceny oryginalnej (domyślnie szary).
     */
    originalPriceColor?: string | null;
    /**
     * Kolor ceny gdy produkt jest w promocji (domyślnie czerwony).
     */
    salePriceColor?: string | null;
  };
  /**
   * Wygląd i zawartość przycisku dodawania produktu do koszyka.
   */
  cartButton?: {
    show?: boolean | null;
    /**
     * Ikona wyświetlana na przycisku dodawania do koszyka.
     */
    icon?: ('ShoppingCart' | 'ShoppingBag' | 'Plus' | 'PlusCircle' | 'PackagePlus') | null;
    /**
     * Tekst na przycisku koszyka. Zostaw puste aby pokazać tylko ikonę.
     */
    label?: string | null;
    /**
     * Domyślnie pokazuje ikonę, tekst pojawia się po najechaniu myszą.
     */
    showLabelOnHover?: boolean | null;
    style?: ('solid' | 'outline' | 'rounded' | 'ghost') | null;
    /**
     * Kolor tła przycisku koszyka (format HEX lub CSS).
     */
    backgroundColor?: string | null;
    textColor?: string | null;
    hoverBackgroundColor?: string | null;
    fontSize?:
      | (
          | '10px'
          | '11px'
          | '12px'
          | '13px'
          | '14px'
          | '15px'
          | '16px'
          | '18px'
          | '20px'
          | '22px'
          | '24px'
          | '28px'
          | '32px'
        )
      | null;
    fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
  };
  /**
   * Styl kontenera (ramki) karty produktu.
   */
  card?: {
    backgroundColor?: string | null;
    borderColor?: string | null;
    borderRadius?: ('0px' | '4px' | '8px' | '12px' | '16px') | null;
    shadow?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
    /**
     * Animacja karty produktu przy najechaniu kursorem.
     */
    hoverEffect?: ('none' | 'lift' | 'scale' | 'shadow' | 'border') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Globalne ustawienia kolorów, typografii i stylu sklepu. Zmiany wpływają na cały wygląd sklepu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  /**
   * Główna paleta kolorów sklepu. Używana w przyciskach, linkach, tłach i akcentach.
   */
  colors?: {
    primary?: {
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      base?: string | null;
      /**
       * Kolor w formacie HEX (np. #374151) lub CSS (np. rgba(0,0,0,0.5)).
       */
      hover?: string | null;
      /**
       * Kolor w formacie HEX (np. #f3f4f6) lub CSS (np. rgba(0,0,0,0.5)).
       */
      light?: string | null;
      /**
       * Kolor w formacie HEX (np. #ffffff) lub CSS (np. rgba(0,0,0,0.5)).
       */
      foreground?: string | null;
    };
    secondary?: {
      /**
       * Kolor w formacie HEX (np. #6b7280) lub CSS (np. rgba(0,0,0,0.5)).
       */
      base?: string | null;
      /**
       * Kolor w formacie HEX (np. #4b5563) lub CSS (np. rgba(0,0,0,0.5)).
       */
      hover?: string | null;
      /**
       * Kolor w formacie HEX (np. #f9fafb) lub CSS (np. rgba(0,0,0,0.5)).
       */
      light?: string | null;
      /**
       * Kolor w formacie HEX (np. #ffffff) lub CSS (np. rgba(0,0,0,0.5)).
       */
      foreground?: string | null;
    };
    accent?: {
      /**
       * Kolor w formacie HEX (np. #f59e0b) lub CSS (np. rgba(0,0,0,0.5)).
       */
      base?: string | null;
      /**
       * Kolor w formacie HEX (np. #d97706) lub CSS (np. rgba(0,0,0,0.5)).
       */
      hover?: string | null;
      /**
       * Kolor w formacie HEX (np. #ffffff) lub CSS (np. rgba(0,0,0,0.5)).
       */
      foreground?: string | null;
    };
    success?: {
      /**
       * Kolor w formacie HEX (np. #10b981) lub CSS (np. rgba(0,0,0,0.5)).
       */
      base?: string | null;
      /**
       * Kolor w formacie HEX (np. #ffffff) lub CSS (np. rgba(0,0,0,0.5)).
       */
      foreground?: string | null;
    };
    danger?: {
      /**
       * Kolor w formacie HEX (np. #ef4444) lub CSS (np. rgba(0,0,0,0.5)).
       */
      base?: string | null;
      /**
       * Kolor w formacie HEX (np. #ffffff) lub CSS (np. rgba(0,0,0,0.5)).
       */
      foreground?: string | null;
    };
    warning?: {
      /**
       * Kolor w formacie HEX (np. #f97316) lub CSS (np. rgba(0,0,0,0.5)).
       */
      base?: string | null;
      /**
       * Kolor w formacie HEX (np. #ffffff) lub CSS (np. rgba(0,0,0,0.5)).
       */
      foreground?: string | null;
    };
    background?: {
      /**
       * Kolor w formacie HEX (np. #ffffff) lub CSS (np. rgba(0,0,0,0.5)).
       */
      page?: string | null;
      /**
       * Kolor w formacie HEX (np. #f9fafb) lub CSS (np. rgba(0,0,0,0.5)).
       */
      section?: string | null;
      /**
       * Kolor w formacie HEX (np. #ffffff) lub CSS (np. rgba(0,0,0,0.5)).
       */
      card?: string | null;
      /**
       * Kolor w formacie HEX (np. rgba(0,0,0,0.5)) lub CSS (np. rgba(0,0,0,0.5)).
       */
      overlay?: string | null;
    };
    text?: {
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      primary?: string | null;
      /**
       * Kolor w formacie HEX (np. #6b7280) lub CSS (np. rgba(0,0,0,0.5)).
       */
      secondary?: string | null;
      /**
       * Kolor w formacie HEX (np. #9ca3af) lub CSS (np. rgba(0,0,0,0.5)).
       */
      muted?: string | null;
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      link?: string | null;
      /**
       * Kolor w formacie HEX (np. #374151) lub CSS (np. rgba(0,0,0,0.5)).
       */
      linkHover?: string | null;
    };
    border?: {
      /**
       * Kolor w formacie HEX (np. #e5e7eb) lub CSS (np. rgba(0,0,0,0.5)).
       */
      default?: string | null;
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      focus?: string | null;
      /**
       * Kolor w formacie HEX (np. #f3f4f6) lub CSS (np. rgba(0,0,0,0.5)).
       */
      divider?: string | null;
    };
    nav?: {
      /**
       * Kolor w formacie HEX (np. #ffffff) lub CSS (np. rgba(0,0,0,0.5)).
       */
      background?: string | null;
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      text?: string | null;
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      activeText?: string | null;
      /**
       * Kolor w formacie HEX (np. #e5e7eb) lub CSS (np. rgba(0,0,0,0.5)).
       */
      border?: string | null;
    };
    footer?: {
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      background?: string | null;
      /**
       * Kolor w formacie HEX (np. #d1d5db) lub CSS (np. rgba(0,0,0,0.5)).
       */
      text?: string | null;
      /**
       * Kolor w formacie HEX (np. #ffffff) lub CSS (np. rgba(0,0,0,0.5)).
       */
      linkHover?: string | null;
      /**
       * Kolor w formacie HEX (np. #374151) lub CSS (np. rgba(0,0,0,0.5)).
       */
      border?: string | null;
    };
  };
  /**
   * Ustawienia czcionek i stylów tekstu. Pamiętaj, że czcionki Google Fonts muszą być załadowane w kodzie strony.
   */
  typography?: {
    /**
     * Czcionka używana dla nagłówków H1-H6.
     */
    headingFont?:
      | (
          | 'Inter, sans-serif'
          | 'Roboto, sans-serif'
          | 'Outfit, sans-serif'
          | 'Poppins, sans-serif'
          | 'Nunito, sans-serif'
          | 'Lato, sans-serif'
          | 'Montserrat, sans-serif'
          | 'Playfair Display, serif'
          | 'Merriweather, serif'
          | 'DM Sans, sans-serif'
          | 'Raleway, sans-serif'
        )
      | null;
    /**
     * Czcionka używana dla paragrafów i ogólnego tekstu.
     */
    bodyFont?:
      | (
          | 'Inter, sans-serif'
          | 'Roboto, sans-serif'
          | 'Outfit, sans-serif'
          | 'Poppins, sans-serif'
          | 'Nunito, sans-serif'
          | 'Lato, sans-serif'
          | 'Montserrat, sans-serif'
          | 'Playfair Display, serif'
          | 'Merriweather, serif'
          | 'DM Sans, sans-serif'
          | 'Raleway, sans-serif'
        )
      | null;
    /**
     * Bazowy rozmiar tekstu (rem base). Wszystkie inne rozmiary są względem tej wartości.
     */
    baseSize?: ('14px' | '15px' | '16px' | '17px' | '18px') | null;
    h1?: {
      /**
       * Rozmiar czcionki dla elementów H1.
       */
      fontSize?:
        | (
            | '14px'
            | '16px'
            | '18px'
            | '20px'
            | '22px'
            | '24px'
            | '28px'
            | '32px'
            | '36px'
            | '40px'
            | '48px'
            | '56px'
            | '64px'
            | '72px'
          )
        | null;
      fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      color?: string | null;
      lineHeight?: ('1.0' | '1.1' | '1.2' | '1.25' | '1.3' | '1.4' | '1.5' | '1.6' | '1.75') | null;
      letterSpacing?: ('-0.05em' | '0' | '0.025em' | '0.05em' | '0.1em' | '0.15em') | null;
      textTransform?: ('none' | 'uppercase' | 'lowercase' | 'capitalize') | null;
    };
    h2?: {
      /**
       * Rozmiar czcionki dla elementów H2.
       */
      fontSize?:
        | (
            | '14px'
            | '16px'
            | '18px'
            | '20px'
            | '22px'
            | '24px'
            | '28px'
            | '32px'
            | '36px'
            | '40px'
            | '48px'
            | '56px'
            | '64px'
            | '72px'
          )
        | null;
      fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      color?: string | null;
      lineHeight?: ('1.0' | '1.1' | '1.2' | '1.25' | '1.3' | '1.4' | '1.5' | '1.6' | '1.75') | null;
      letterSpacing?: ('-0.05em' | '0' | '0.025em' | '0.05em' | '0.1em' | '0.15em') | null;
      textTransform?: ('none' | 'uppercase' | 'lowercase' | 'capitalize') | null;
    };
    h3?: {
      /**
       * Rozmiar czcionki dla elementów H3.
       */
      fontSize?:
        | (
            | '14px'
            | '16px'
            | '18px'
            | '20px'
            | '22px'
            | '24px'
            | '28px'
            | '32px'
            | '36px'
            | '40px'
            | '48px'
            | '56px'
            | '64px'
            | '72px'
          )
        | null;
      fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      color?: string | null;
      lineHeight?: ('1.0' | '1.1' | '1.2' | '1.25' | '1.3' | '1.4' | '1.5' | '1.6' | '1.75') | null;
      letterSpacing?: ('-0.05em' | '0' | '0.025em' | '0.05em' | '0.1em' | '0.15em') | null;
      textTransform?: ('none' | 'uppercase' | 'lowercase' | 'capitalize') | null;
    };
    h4?: {
      /**
       * Rozmiar czcionki dla elementów H4.
       */
      fontSize?:
        | (
            | '14px'
            | '16px'
            | '18px'
            | '20px'
            | '22px'
            | '24px'
            | '28px'
            | '32px'
            | '36px'
            | '40px'
            | '48px'
            | '56px'
            | '64px'
            | '72px'
          )
        | null;
      fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      color?: string | null;
      lineHeight?: ('1.0' | '1.1' | '1.2' | '1.25' | '1.3' | '1.4' | '1.5' | '1.6' | '1.75') | null;
      letterSpacing?: ('-0.05em' | '0' | '0.025em' | '0.05em' | '0.1em' | '0.15em') | null;
      textTransform?: ('none' | 'uppercase' | 'lowercase' | 'capitalize') | null;
    };
    h5?: {
      /**
       * Rozmiar czcionki dla elementów H5.
       */
      fontSize?:
        | (
            | '14px'
            | '16px'
            | '18px'
            | '20px'
            | '22px'
            | '24px'
            | '28px'
            | '32px'
            | '36px'
            | '40px'
            | '48px'
            | '56px'
            | '64px'
            | '72px'
          )
        | null;
      fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      color?: string | null;
      lineHeight?: ('1.0' | '1.1' | '1.2' | '1.25' | '1.3' | '1.4' | '1.5' | '1.6' | '1.75') | null;
      letterSpacing?: ('-0.05em' | '0' | '0.025em' | '0.05em' | '0.1em' | '0.15em') | null;
      textTransform?: ('none' | 'uppercase' | 'lowercase' | 'capitalize') | null;
    };
    h6?: {
      /**
       * Rozmiar czcionki dla elementów H6.
       */
      fontSize?:
        | (
            | '14px'
            | '16px'
            | '18px'
            | '20px'
            | '22px'
            | '24px'
            | '28px'
            | '32px'
            | '36px'
            | '40px'
            | '48px'
            | '56px'
            | '64px'
            | '72px'
          )
        | null;
      fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
      /**
       * Kolor w formacie HEX (np. #111827) lub CSS (np. rgba(0,0,0,0.5)).
       */
      color?: string | null;
      lineHeight?: ('1.0' | '1.1' | '1.2' | '1.25' | '1.3' | '1.4' | '1.5' | '1.6' | '1.75') | null;
      letterSpacing?: ('-0.05em' | '0' | '0.025em' | '0.05em' | '0.1em' | '0.15em') | null;
      textTransform?: ('none' | 'uppercase' | 'lowercase' | 'capitalize') | null;
    };
    /**
     * Styl domyślnego tekstu paragrafów.
     */
    body?: {
      fontSize?: ('13px' | '14px' | '15px' | '16px' | '17px' | '18px') | null;
      fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
      /**
       * Kolor w formacie HEX (np. #374151) lub CSS (np. rgba(0,0,0,0.5)).
       */
      color?: string | null;
      lineHeight?: ('1.4' | '1.5' | '1.6' | '1.7' | '1.75' | '1.8' | '2.0') | null;
    };
    /**
     * Styl małego tekstu pomocniczego (etykiety, podpisy).
     */
    small?: {
      fontSize?: ('10px' | '11px' | '12px' | '13px') | null;
      fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
      /**
       * Kolor w formacie HEX (np. #6b7280) lub CSS (np. rgba(0,0,0,0.5)).
       */
      color?: string | null;
    };
  };
  /**
   * Ogólne ustawienia stylu dotyczące całej strony.
   */
  globalStyles?: {
    /**
     * Bazowy promień zaokrąglenia rogów przycisków, kart, pól itp.
     */
    borderRadius?: ('0px' | '4px' | '8px' | '12px' | '16px' | '9999px') | null;
    buttonStyle?: ('solid' | 'outline' | 'ghost' | 'soft') | null;
    /**
     * Globalny czas trwania animacji CSS (hover, fokus, itp.).
     */
    transitionSpeed?: ('0ms' | '100ms' | '200ms' | '300ms' | '500ms') | null;
    /**
     * Maksymalna szerokość głównego kontenera treści.
     */
    containerMaxWidth?: ('1024px' | '1200px' | '1280px' | '1400px' | '1536px' | '100%') | null;
    /**
     * Pionowy odstęp między sekcjami na stronach.
     */
    sectionSpacing?: ('32px' | '48px' | '64px' | '80px' | '96px') | null;
  };
  /**
   * Ustawienia kolorów dla trybu ciemnego (jeśli sklep obsługuje dark mode).
   */
  darkMode?: {
    /**
     * Aktywuj ciemny motyw po wykryciu preferencji systemowych użytkownika.
     */
    enabled?: boolean | null;
    /**
     * Kolor w formacie HEX (np. #0f172a) lub CSS (np. rgba(0,0,0,0.5)).
     */
    background?: string | null;
    /**
     * Kolor w formacie HEX (np. #1e293b) lub CSS (np. rgba(0,0,0,0.5)).
     */
    cardBackground?: string | null;
    /**
     * Kolor w formacie HEX (np. #f1f5f9) lub CSS (np. rgba(0,0,0,0.5)).
     */
    textPrimary?: string | null;
    /**
     * Kolor w formacie HEX (np. #94a3b8) lub CSS (np. rgba(0,0,0,0.5)).
     */
    textSecondary?: string | null;
    /**
     * Kolor w formacie HEX (np. #334155) lub CSS (np. rgba(0,0,0,0.5)).
     */
    border?: string | null;
    /**
     * Kolor w formacie HEX (np. #6366f1) lub CSS (np. rgba(0,0,0,0.5)).
     */
    primary?: string | null;
    /**
     * Kolor w formacie HEX (np. #4f46e5) lub CSS (np. rgba(0,0,0,0.5)).
     */
    primaryHover?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-info_select".
 */
export interface StoreInfoSelect<T extends boolean = true> {
  storeName?: T;
  logo?: T;
  tagline?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        tiktok?: T;
        youtube?: T;
        x?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        favicon?: T;
      };
  businessInfo?:
    | T
    | {
        companyName?: T;
        nip?: T;
        regon?: T;
        bankAccount?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  homePage?:
    | T
    | {
        blocks?:
          | T
          | {
              'product-carousel'?:
                | T
                | {
                    heading?: T;
                    icon?: T;
                    sourceType?: T;
                    category?: T;
                    collectionHandle?: T;
                    manualProducts?: T;
                    visibleCount?: T;
                    showViewAllButton?: T;
                    viewAllLabel?: T;
                    viewAllUrl?: T;
                    id?: T;
                    blockName?: T;
                  };
              'category-carousel'?:
                | T
                | {
                    heading?: T;
                    icon?: T;
                    sourceType?: T;
                    categories?: T;
                    visibleCount?: T;
                    categoryUrlPrefix?: T;
                    id?: T;
                    blockName?: T;
                  };
              'latest-blogs'?:
                | T
                | {
                    heading?: T;
                    icon?: T;
                    postsCount?: T;
                    filterByCategory?: T;
                    category?: T;
                    showViewAllButton?: T;
                    viewAllLabel?: T;
                    viewAllUrl?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-card-settings_select".
 */
export interface ProductCardSettingsSelect<T extends boolean = true> {
  image?:
    | T
    | {
        show?: T;
        aspectRatio?: T;
        borderRadius?: T;
      };
  productName?:
    | T
    | {
        show?: T;
        fontSize?: T;
        fontWeight?: T;
        color?: T;
        maxLines?: T;
      };
  category?:
    | T
    | {
        show?: T;
        fontSize?: T;
        fontWeight?: T;
        color?: T;
      };
  price?:
    | T
    | {
        show?: T;
        fontSize?: T;
        fontWeight?: T;
        color?: T;
        showOriginalPrice?: T;
        originalPriceColor?: T;
        salePriceColor?: T;
      };
  cartButton?:
    | T
    | {
        show?: T;
        icon?: T;
        label?: T;
        showLabelOnHover?: T;
        style?: T;
        backgroundColor?: T;
        textColor?: T;
        hoverBackgroundColor?: T;
        fontSize?: T;
        fontWeight?: T;
      };
  card?:
    | T
    | {
        backgroundColor?: T;
        borderColor?: T;
        borderRadius?: T;
        shadow?: T;
        hoverEffect?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  colors?:
    | T
    | {
        primary?:
          | T
          | {
              base?: T;
              hover?: T;
              light?: T;
              foreground?: T;
            };
        secondary?:
          | T
          | {
              base?: T;
              hover?: T;
              light?: T;
              foreground?: T;
            };
        accent?:
          | T
          | {
              base?: T;
              hover?: T;
              foreground?: T;
            };
        success?:
          | T
          | {
              base?: T;
              foreground?: T;
            };
        danger?:
          | T
          | {
              base?: T;
              foreground?: T;
            };
        warning?:
          | T
          | {
              base?: T;
              foreground?: T;
            };
        background?:
          | T
          | {
              page?: T;
              section?: T;
              card?: T;
              overlay?: T;
            };
        text?:
          | T
          | {
              primary?: T;
              secondary?: T;
              muted?: T;
              link?: T;
              linkHover?: T;
            };
        border?:
          | T
          | {
              default?: T;
              focus?: T;
              divider?: T;
            };
        nav?:
          | T
          | {
              background?: T;
              text?: T;
              activeText?: T;
              border?: T;
            };
        footer?:
          | T
          | {
              background?: T;
              text?: T;
              linkHover?: T;
              border?: T;
            };
      };
  typography?:
    | T
    | {
        headingFont?: T;
        bodyFont?: T;
        baseSize?: T;
        h1?:
          | T
          | {
              fontSize?: T;
              fontWeight?: T;
              color?: T;
              lineHeight?: T;
              letterSpacing?: T;
              textTransform?: T;
            };
        h2?:
          | T
          | {
              fontSize?: T;
              fontWeight?: T;
              color?: T;
              lineHeight?: T;
              letterSpacing?: T;
              textTransform?: T;
            };
        h3?:
          | T
          | {
              fontSize?: T;
              fontWeight?: T;
              color?: T;
              lineHeight?: T;
              letterSpacing?: T;
              textTransform?: T;
            };
        h4?:
          | T
          | {
              fontSize?: T;
              fontWeight?: T;
              color?: T;
              lineHeight?: T;
              letterSpacing?: T;
              textTransform?: T;
            };
        h5?:
          | T
          | {
              fontSize?: T;
              fontWeight?: T;
              color?: T;
              lineHeight?: T;
              letterSpacing?: T;
              textTransform?: T;
            };
        h6?:
          | T
          | {
              fontSize?: T;
              fontWeight?: T;
              color?: T;
              lineHeight?: T;
              letterSpacing?: T;
              textTransform?: T;
            };
        body?:
          | T
          | {
              fontSize?: T;
              fontWeight?: T;
              color?: T;
              lineHeight?: T;
            };
        small?:
          | T
          | {
              fontSize?: T;
              fontWeight?: T;
              color?: T;
            };
      };
  globalStyles?:
    | T
    | {
        borderRadius?: T;
        buttonStyle?: T;
        transitionSpeed?: T;
        containerMaxWidth?: T;
        sectionSpacing?: T;
      };
  darkMode?:
    | T
    | {
        enabled?: T;
        background?: T;
        cardBackground?: T;
        textPrimary?: T;
        textSecondary?: T;
        border?: T;
        primary?: T;
        primaryHover?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}